Repository kubevirt/common-instancetypes, pull requests merged in 2022-11, with the labels that each got.

#6 Add 0xFelix to approvers
  OWNERS
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#5 check: Add pwd as safe git directory
  image/Dockerfile
  scripts/check.sh
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#7 push_image: Build and push with a consistent tag
  Makefile
  scripts/push_image.sh
Labels: dco-signoff: yes, lgtm, size/XS, release-note-none

#8 workflow: Fix yamllint errors
  .github/workflows/release.yaml
Labels: dco-signoff: yes, size/XS, release-note-none

#10 image: Add shellcheck to the image
  image/Dockerfile
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#4 Add Windows Server 2022 preferences
  README.md
  common-clusterpreferences-bundle.yaml
  common-instancetypes-all-bundle.yaml
  common-instancetypes/preferences/windows/2k22/kustomization.yaml
  common-instancetypes/preferences/windows/2k22_virtio/kustomization.yaml
  common-instancetypes/preferences/windows/kustomization.yaml
  common-preferences-bundle.yaml
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#9 cri: Use private unshared label for bind mount
  scripts/cri.sh
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#11 scripts: Use shellcheck within lint.sh and fix issues
  README.md
  image/Dockerfile
  scripts/build_image.sh
  scripts/cri.sh
  scripts/generate.sh
  scripts/lint.sh
  scripts/push_image.sh
  scripts/readme.sh
  scripts/schema.sh
  scripts/validate.sh
Labels: dco-signoff: yes, size/M, lgtm, approved, release-note-none

#12 Fix micro size label typo
  common-clusterinstancetypes-bundle.yaml
  common-instancetypes-all-bundle.yaml
  common-instancetypes-bundle.yaml
  common-instancetypes/instancetypes/sizes/micro/micro.yaml
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none
