Repository kubevirt/common-instancetypes, pull requests merged in 2023-07, with the labels that each got.

#77 chore: add more reviewers
  OWNERS
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#78 chore: stop using deprecated cdi-insecure-registries configmap
  scripts/kubevirtci.sh
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#83 fix: Add missing resource labels to O instance types
  common-clusterinstancetypes-bundle.yaml
  common-instancetypes-all-bundle.yaml
  common-instancetypes-bundle.yaml
  common-instancetypes/instancetypes/o/sizes/2xlarge/2xlarge.yaml
  common-instancetypes/instancetypes/o/sizes/4xlarge/4xlarge.yaml
  common-instancetypes/instancetypes/o/sizes/8xlarge/8xlarge.yaml
  common-instancetypes/instancetypes/o/sizes/large/large.yaml
  common-instancetypes/instancetypes/o/sizes/medium/medium.yaml
  common-instancetypes/instancetypes/o/sizes/xlarge/xlarge.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved, release-note-none

#81 [release-0.3] chore: Pin KubeVirt to v1.0.0
  Makefile
  scripts/kubevirt.sh
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#86 feat: Add u1.{small,micro,nano} instancetypes
  README.md
  common-clusterinstancetypes-bundle.yaml
  common-instancetypes-all-bundle.yaml
  common-instancetypes-bundle.yaml
  common-instancetypes/instancetypes/u/1/kustomization.yaml
  common-instancetypes/instancetypes/u/1/micro/kustomization.yaml
  common-instancetypes/instancetypes/u/1/nano/kustomization.yaml
  common-instancetypes/instancetypes/u/1/small/kustomization.yaml
  common-instancetypes/instancetypes/u/sizes/micro/kustomization.yaml
  common-instancetypes/instancetypes/u/sizes/micro/micro.yaml
  common-instancetypes/instancetypes/u/sizes/nano/kustomization.yaml
  common-instancetypes/instancetypes/u/sizes/nano/nano.yaml
  common-instancetypes/instancetypes/u/sizes/small/kustomization.yaml
  common-instancetypes/instancetypes/u/sizes/small/small.yaml
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#89 lint: Ensure we exit 1 on failure
  scripts/lint.sh
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#91 Move instancetype.kubevirt.io/{class,version} to labels
  common-clusterinstancetypes-bundle.yaml
  common-instancetypes-all-bundle.yaml
  common-instancetypes-bundle.yaml
  instancetypes/cx/1/cx1.yaml
  instancetypes/gn/1/gn1.yaml
  instancetypes/m/1/m1.yaml
  instancetypes/o/1/o1.yaml
  instancetypes/u/1/u1.yaml
Labels: dco-signoff: yes, lgtm, release-note, size/XL, approved

#92 Assorted cleanups after the recent flattening
  instancetypes/u/sizes/micro/kustomization.yaml
  instancetypes/u/sizes/micro/micro.yaml
  instancetypes/u/sizes/nano/kustomization.yaml
  instancetypes/u/sizes/nano/nano.yaml
  instancetypes/u/sizes/small/kustomization.yaml
  instancetypes/u/sizes/small/small.yaml
  scripts/check.sh
Labels: dco-signoff: yes, size/M, lgtm, approved, release-note-none

#93 instancetypes: Sync O with U after new sizes were introduced
  README.md
  common-clusterinstancetypes-bundle.yaml
  common-instancetypes-all-bundle.yaml
  common-instancetypes-bundle.yaml
  instancetypes/o/1/sizes.yaml
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#94 github: Use main for SSP operator sync PR
  .github/workflows/release.yaml
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none
