Repository kubevirt/common-instancetypes, pull requests merged in 2023-06, with the labels that each got.

#44 Move to v1beta1
  README.md
  VirtualMachineClusterInstancetypes/kustomization.yaml
  VirtualMachineClusterPreferences/kustomization.yaml
  VirtualMachineInstancetypes/kustomization.yaml
  VirtualMachinePreferences/kustomization.yaml
  common-clusterinstancetypes-bundle.yaml
  common-clusterpreferences-bundle.yaml
  common-instancetypes-all-bundle.yaml
  common-instancetypes/instancetypes/base/VirtualMachineClusterInstancetype.yaml
  common-instancetypes/instancetypes/hyperscale/cx/1/base/cx1.yaml
  common-instancetypes/instancetypes/hyperscale/cx/sizes/2xlarge/2xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/cx/sizes/4xlarge/4xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/cx/sizes/8xlarge/8xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/cx/sizes/large/large.yaml
  common-instancetypes/instancetypes/hyperscale/cx/sizes/medium/medium.yaml
  common-instancetypes/instancetypes/hyperscale/cx/sizes/xlarge/xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/gn/1/base/gn1.yaml
  common-instancetypes/instancetypes/hyperscale/gn/base/gn.yaml
  common-instancetypes/instancetypes/hyperscale/gn/sizes/2xlarge/2xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/gn/sizes/4xlarge/4xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/gn/sizes/8xlarge/8xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/gn/sizes/xlarge/xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/m/1/base/m1.yaml
  common-instancetypes/instancetypes/hyperscale/m/base/m.yaml
  common-instancetypes/instancetypes/hyperscale/m/sizes/2xlarge/2xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/m/sizes/4xlarge/4xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/m/sizes/8xlarge/8xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/m/sizes/large/large.yaml
  common-instancetypes/instancetypes/hyperscale/m/sizes/xlarge/xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/n/1/base/n1.yaml
  common-instancetypes/instancetypes/hyperscale/n/base/n.yaml
  common-instancetypes/instancetypes/hyperscale/n/sizes/2xlarge/2xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/n/sizes/4xlarge/4xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/n/sizes/8xlarge/8xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/n/sizes/large/large.yaml
  common-instancetypes/instancetypes/hyperscale/n/sizes/medium/medium.yaml
  common-instancetypes/instancetypes/hyperscale/n/sizes/xlarge/xlarge.yaml
  common-instancetypes/preferences/base/VirtualMachineClusterPreference.yaml
  common-instancetypes/preferences/base/VirtualMachinePreference.yaml
  common-preferences-bundle.yaml
Labels: dco-signoff: yes, lgtm, size/XXL, release-note, approved

#45 Preferred termination grace period seconds
  common-clusterpreferences-bundle.yaml
  common-instancetypes-all-bundle.yaml
  common-instancetypes/preferences/components/termination-grace-period/kustomization.yaml
  common-instancetypes/preferences/components/termination-grace-period/termination-grace-period.yaml
  common-instancetypes/preferences/windows/base/kustomization.yaml
  common-preferences-bundle.yaml
Labels: dco-signoff: yes, size/M, lgtm, release-note, approved

#49 Add resource labels to hyperscale instance types
  common-clusterinstancetypes-bundle.yaml
  common-instancetypes-all-bundle.yaml
  common-instancetypes-bundle.yaml
  common-instancetypes/instancetypes/hyperscale/cx/base/cx.yaml
  common-instancetypes/instancetypes/hyperscale/cx/sizes/2xlarge/2xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/cx/sizes/4xlarge/4xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/cx/sizes/8xlarge/8xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/cx/sizes/large/large.yaml
  common-instancetypes/instancetypes/hyperscale/cx/sizes/medium/medium.yaml
  common-instancetypes/instancetypes/hyperscale/cx/sizes/xlarge/xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/gn/base/gn.yaml
  common-instancetypes/instancetypes/hyperscale/gn/sizes/2xlarge/2xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/gn/sizes/4xlarge/4xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/gn/sizes/8xlarge/8xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/gn/sizes/xlarge/xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/m/base/m.yaml
  common-instancetypes/instancetypes/hyperscale/m/sizes/2xlarge/2xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/m/sizes/4xlarge/4xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/m/sizes/8xlarge/8xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/m/sizes/large/large.yaml
  common-instancetypes/instancetypes/hyperscale/m/sizes/xlarge/xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/n/sizes/2xlarge/2xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/n/sizes/4xlarge/4xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/n/sizes/8xlarge/8xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/n/sizes/large/large.yaml
  common-instancetypes/instancetypes/hyperscale/n/sizes/medium/medium.yaml
  common-instancetypes/instancetypes/hyperscale/n/sizes/xlarge/xlarge.yaml
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#57 fix: Use v1beta1 in base VirtualMachineInstancetype definition
  README.md
  common-instancetypes-all-bundle.yaml
  common-instancetypes-bundle.yaml
  common-instancetypes/instancetypes/base/VirtualMachineInstancetype.yaml
  common-instancetypes/instancetypes/legacy/deprecated/deprecated.yaml
  common-instancetypes/instancetypes/legacy/highperformance/base/highperformance.yaml
  common-instancetypes/instancetypes/legacy/sizes/large/large.yaml
  common-instancetypes/instancetypes/legacy/sizes/medium/medium.yaml
  common-instancetypes/instancetypes/legacy/sizes/micro/micro.yaml
  common-instancetypes/instancetypes/legacy/sizes/small/small.yaml
  common-instancetypes/instancetypes/legacy/sizes/tiny/tiny.yaml
  common-instancetypes/preferences/alpine/metadata/metadata.yaml
  common-instancetypes/preferences/base/metadata/metadata.yaml
  common-instancetypes/preferences/centos/7/metadata/metadata.yaml
  common-instancetypes/preferences/centos/8_stream/metadata/metadata.yaml
  common-instancetypes/preferences/centos/9_stream/metadata/metadata.yaml
  common-instancetypes/preferences/centos/base/metadata/metadata.yaml
  common-instancetypes/preferences/cirros/metadata/metadata.yaml
  common-instancetypes/preferences/components/cpu-topology-sockets/cpu-topology-sockets.yaml
  common-instancetypes/preferences/components/disk-dedicatediothread/dedicatediothread.yaml
  common-instancetypes/preferences/components/diskbus-sata/diskbus-sata.yaml
  common-instancetypes/preferences/components/diskbus-virtio-blk/diskbus-virtio-blk.yaml
  common-instancetypes/preferences/components/hyperv/hyperv.yaml
  common-instancetypes/preferences/components/interface-multiqueue/interface-multiqueue.yaml
  common-instancetypes/preferences/components/interfacemodel-e1000e/e1000e.yaml
  common-instancetypes/preferences/components/interfacemodel-virtio-net/interfacemodel-virtio-net.yaml
  common-instancetypes/preferences/components/rng/rng.yaml
  common-instancetypes/preferences/components/secureboot/secureboot.yaml
  common-instancetypes/preferences/components/tablet-usb/tablet-usb.yaml
  common-instancetypes/preferences/components/tablet-virtio/tablet-virtio.yaml
  common-instancetypes/preferences/components/termination-grace-period/termination-grace-period.yaml
  common-instancetypes/preferences/components/tpm/tpm.yaml
  common-instancetypes/preferences/fedora/metadata/metadata.yaml
  common-instancetypes/preferences/rhel/7/metadata/metadata.yaml
  common-instancetypes/preferences/rhel/8/metadata/metadata.yaml
  common-instancetypes/preferences/rhel/9/metadata/metadata.yaml
  common-instancetypes/preferences/rhel/base/metadata/metadata.yaml
  common-instancetypes/preferences/ubuntu/metadata/metadata.yaml
  common-instancetypes/preferences/windows/10/metadata/metadata.yaml
  common-instancetypes/preferences/windows/10_virtio/metadata/metadata.yaml
  common-instancetypes/preferences/windows/11/metadata/metadata.yaml
  common-instancetypes/preferences/windows/11_virtio/metadata/metadata.yaml
  common-instancetypes/preferences/windows/2k12/metadata/metadata.yaml
  common-instancetypes/preferences/windows/2k12_virtio/metadata/metadata.yaml
  common-instancetypes/preferences/windows/2k16/metadata/metadata.yaml
  common-instancetypes/preferences/windows/2k16_virtio/metadata/metadata.yaml
  common-instancetypes/preferences/windows/2k19/metadata/metadata.yaml
  common-instancetypes/preferences/windows/2k19_virtio/metadata/metadata.yaml
  common-instancetypes/preferences/windows/2k22/metadata/metadata.yaml
  common-instancetypes/preferences/windows/2k22_virtio/metadata/metadata.yaml
  common-instancetypes/preferences/windows/base/metadata/metadata.yaml
  scripts/check.sh
Labels: dco-signoff: yes, lgtm, size/XXL, approved, release-note-none

#58 Introduce preference resource requirements
  common-clusterpreferences-bundle.yaml
  common-instancetypes-all-bundle.yaml
  common-instancetypes/preferences/alpine/kustomization.yaml
  common-instancetypes/preferences/alpine/requirements/kustomization.yaml
  common-instancetypes/preferences/alpine/requirements/requirements.yaml
  common-instancetypes/preferences/centos/7/kustomization.yaml
  common-instancetypes/preferences/centos/7/requirements/kustomization.yaml
  common-instancetypes/preferences/centos/7/requirements/requirements.yaml
  common-instancetypes/preferences/centos/8_stream/kustomization.yaml
  common-instancetypes/preferences/centos/8_stream/requirements/kustomization.yaml
  common-instancetypes/preferences/centos/8_stream/requirements/requirements.yaml
  common-instancetypes/preferences/centos/9_stream/kustomization.yaml
  common-instancetypes/preferences/centos/9_stream/requirements/kustomization.yaml
  common-instancetypes/preferences/centos/9_stream/requirements/requirements.yaml
  common-instancetypes/preferences/cirros/kustomization.yaml
  common-instancetypes/preferences/cirros/requirements/kustomization.yaml
  common-instancetypes/preferences/cirros/requirements/requirements.yaml
  common-instancetypes/preferences/fedora/kustomization.yaml
  common-instancetypes/preferences/fedora/requirements/kustomization.yaml
  common-instancetypes/preferences/fedora/requirements/requirements.yaml
  common-instancetypes/preferences/rhel/7/kustomization.yaml
  common-instancetypes/preferences/rhel/7/requirements/kustomization.yaml
  common-instancetypes/preferences/rhel/7/requirements/requirements.yaml
  common-instancetypes/preferences/rhel/8/kustomization.yaml
  common-instancetypes/preferences/rhel/8/requirements/kustomization.yaml
  common-instancetypes/preferences/rhel/8/requirements/requirements.yaml
  common-instancetypes/preferences/rhel/9/kustomization.yaml
  common-instancetypes/preferences/rhel/9/requirements/kustomization.yaml
  common-instancetypes/preferences/rhel/9/requirements/requirements.yaml
  common-instancetypes/preferences/ubuntu/kustomization.yaml
  common-instancetypes/preferences/ubuntu/requirements/kustomization.yaml
  common-instancetypes/preferences/ubuntu/requirements/requirements.yaml
  common-instancetypes/preferences/windows/10/kustomization.yaml
  common-instancetypes/preferences/windows/10/requirements/kustomization.yaml
  common-instancetypes/preferences/windows/10/requirements/requirements.yaml
  common-instancetypes/preferences/windows/11/requirements/kustomization.yaml
  common-instancetypes/preferences/windows/11/requirements/requirements.yaml
  common-instancetypes/preferences/windows/2k12/kustomization.yaml
  common-instancetypes/preferences/windows/2k12/requirements/kustomization.yaml
  common-instancetypes/preferences/windows/2k12/requirements/requirements.yaml
  common-instancetypes/preferences/windows/2k16/requirements/kustomization.yaml
  common-instancetypes/preferences/windows/2k16/requirements/requirements.yaml
  common-instancetypes/preferences/windows/2k19/kustomization.yaml
  common-instancetypes/preferences/windows/2k19/requirements/kustomization.yaml
  common-instancetypes/preferences/windows/2k19/requirements/requirements.yaml
  common-instancetypes/preferences/windows/2k22/kustomization.yaml
  common-instancetypes/preferences/windows/2k22/requirements/kustomization.yaml
  common-instancetypes/preferences/windows/2k22/requirements/requirements.yaml
  common-preferences-bundle.yaml
  scripts/functest.sh
  scripts/kubevirt.sh
  scripts/kubevirtci.sh
Labels: dco-signoff: yes, lgtm, release-note, size/XL, approved

#48 Introduce a new `O` Overcommitted instance type class
  README.md
  common-clusterinstancetypes-bundle.yaml
  common-instancetypes-all-bundle.yaml
  common-instancetypes-bundle.yaml
  common-instancetypes/instancetypes/hyperscale/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/o/1/2xlarge/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/o/1/4xlarge/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/o/1/8xlarge/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/o/1/base/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/o/1/base/o1.yaml
  common-instancetypes/instancetypes/hyperscale/o/1/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/o/1/large/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/o/1/medium/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/o/1/xlarge/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/o/base/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/o/base/o.yaml
  common-instancetypes/instancetypes/hyperscale/o/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/o/sizes/2xlarge/2xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/o/sizes/2xlarge/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/o/sizes/4xlarge/4xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/o/sizes/4xlarge/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/o/sizes/8xlarge/8xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/o/sizes/8xlarge/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/o/sizes/large/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/o/sizes/large/large.yaml
  common-instancetypes/instancetypes/hyperscale/o/sizes/medium/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/o/sizes/medium/medium.yaml
  common-instancetypes/instancetypes/hyperscale/o/sizes/xlarge/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/o/sizes/xlarge/xlarge.yaml
Labels: dco-signoff: yes, lgtm, release-note, size/XL, approved

#61 OWNERS: Add lyarwood and 0xFelix as reviewers
  OWNERS
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#63 Rename the Neutral instance type class to Universal
  README.md
  common-clusterinstancetypes-bundle.yaml
  common-instancetypes-all-bundle.yaml
  common-instancetypes-bundle.yaml
  common-instancetypes/instancetypes/hyperscale/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/u/1/2xlarge/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/u/1/4xlarge/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/u/1/8xlarge/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/u/1/base/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/u/1/base/n1.yaml
  common-instancetypes/instancetypes/hyperscale/u/1/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/u/1/large/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/u/1/medium/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/u/1/xlarge/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/u/base/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/u/base/u.yaml
  common-instancetypes/instancetypes/hyperscale/u/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/u/sizes/2xlarge/2xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/u/sizes/2xlarge/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/u/sizes/4xlarge/4xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/u/sizes/4xlarge/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/u/sizes/8xlarge/8xlarge.yaml
  common-instancetypes/instancetypes/hyperscale/u/sizes/8xlarge/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/u/sizes/large/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/u/sizes/large/large.yaml
  common-instancetypes/instancetypes/hyperscale/u/sizes/medium/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/u/sizes/medium/medium.yaml
  common-instancetypes/instancetypes/hyperscale/u/sizes/xlarge/kustomization.yaml
  common-instancetypes/instancetypes/hyperscale/u/sizes/xlarge/xlarge.yaml
  scripts/functest.sh
Labels: dco-signoff: yes, lgtm, size/XXL, release-note, approved

#64 github: Fix bundle version labelling
  .github/workflows/release.yaml
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#68 Fix type in O series description
  common-clusterinstancetypes-bundle.yaml
  common-instancetypes-all-bundle.yaml
  common-instancetypes-bundle.yaml
  common-instancetypes/instancetypes/hyperscale/o/base/o.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved, release-note-none, ok-to-test

#70 [release-0.3] Pin KubeVirt to v1.0.0-rc.0 until GA
  scripts/kubevirt.sh
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none
