Repository kubevirt/common-instancetypes, pull requests merged in 2023-12, with the labels that each got.

#131 Add a comment about long termination period for Windows
  preferences/windows/base/kustomization.yaml
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#133 image: Add tar to image
  image/Dockerfile
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#132 feat: Add golangci-lint for tests
  .golangci.yml
  .pre-commit-config.yaml
  DEVELOPMENT.md
  Makefile
  scripts/check-tree-clean.sh
  scripts/check.sh
  tests/functests/instancetype_test.go
  tests/unittests/instancetype_test.go
  tests/unittests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/L, approved, release-note-none

#134 Cosmetic fixes
  preferences/windows/base/kustomization.yaml
  tests/unittests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#137 Add missing reporters and flags to functests
  tests/functests/test_suite_test.go
  tests/go.mod
  tests/go.sum
  tests/vendor/kubevirt.io/qe-tools/LICENSE
  tests/vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  tests/vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
  tests/vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  tests/vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
  tests/vendor/modules.txt
Labels: dco-signoff: yes, lgtm, size/XL, approved, release-note-none

#138 chore: Randomize functests and be more verbose
  Makefile
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#139 feat: Add pf-icon labels to instancetypes
  instancetypes/cx/1/cx1.yaml
  instancetypes/gn/1/gn1.yaml
  instancetypes/m/1/m1.yaml
  instancetypes/n/1/n1.yaml
  instancetypes/o/1/o1.yaml
  instancetypes/u/1/u1.yaml
Labels: dco-signoff: yes, lgtm, size/XS, release-note, approved

#136 feat: Add functest for the windows.11 preference
  Makefile
  image/validationos.Dockerfile
  scripts/kubevirt.sh
  scripts/kubevirtci.sh
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/L, approved, release-note-none

#140 fix: Pull containerdisks before pushing them
  scripts/kubevirt.sh
  scripts/kubevirtci.sh
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#141 chore: Add test ids to functional tests
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#142 feat: Allow to use fixed versions of KubeVirt and kubevirtci
  scripts/kubevirtci.sh
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#143 chore: Fix KubeVirt and kubevirtci versions
  Makefile
Labels: dco-signoff: yes, size/XS, release-note-none
