Repository kubevirt/common-instancetypes, pull requests merged in 2024-01, with the labels that each got.

#144 fix: Replace names in checksum file during release
  .github/scripts/build.sh
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#145 chore: Remove nodeselector from N instancetypes
  instancetypes/n/1/n1.yaml
Labels: dco-signoff: yes, lgtm, size/XS, release-note, approved

#147 Update Windows 10 preference to allow for boot from UEFI with TPM
  preferences/windows/10/kustomization.yaml
Labels: dco-signoff: yes, lgtm, size/XS, release-note, approved

#149 fix: Remove TPM from Windows 10 preference
  preferences/windows/10/kustomization.yaml
Labels: dco-signoff: yes, lgtm, size/XS, release-note, approved

#148 Add Windows functional tests
  .gitignore
  image/build_windows_containerdisk.sh
  image/overlays/generic/post-install.ps1
  image/overlays/windows10/autounattend.xml
  image/overlays/windows11/autounattend.xml
  image/overlays/windows2k16/autounattend.xml
  image/overlays/windows2k16/post-install.ps1
  image/overlays/windows2k19/autounattend.xml
  image/overlays/windows2k22/autounattend.xml
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/XL, approved, release-note-none

#151 feat: Use virtio in Windows functional tests
  image/build_windows_containerdisk.sh
  image/overlays/windows10/autounattend.xml
  image/overlays/windows11/autounattend.xml
  image/overlays/windows2k16/autounattend.xml
  image/overlays/windows2k19/autounattend.xml
  image/overlays/windows2k22/autounattend.xml
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, size/M, lgtm, approved, release-note-none

#153 feat: Add labels to windows containerdisks
  image/build_windows_containerdisk.sh
  image/validationos.Dockerfile
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#154 Remove 'codingben' from OWNERS
  OWNERS
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none
