Repository kubevirt/common-instancetypes, pull requests merged in 2024-12, with the labels that each got.

#297 fedora: Remove use of interface multiqueue
  preferences/fedora/amd64/kustomization.yaml
  preferences/fedora/arm64/kustomization.yaml
  preferences/fedora/s390x/kustomization.yaml
Labels: dco-signoff: yes, lgtm, size/XS, release-note, approved

#303 chore(builder): Bump to Fedora 41
  image/Dockerfile
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#302 chore(deps): Bump go.mod
  .golangci.yml
  Makefile
  tests/functests/instancetype_test.go
  tests/go.mod
  tools/go.mod
Labels: dco-signoff: yes, size/M, lgtm, approved, release-note-none

#305 chore(test): Add CentOS Stream 10 func test.
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#306 chore(go.mod): Replace golang.org/x/net v0.32.0 with v0.33.0
  tools/go.mod
  tools/go.sum
  tools/vendor/golang.org/x/net/html/doctype.go
  tools/vendor/golang.org/x/net/html/foreign.go
  tools/vendor/golang.org/x/net/html/parse.go
  tools/vendor/modules.txt
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#307 [release-1.2] Backport s390x support
  README.md
  preferences/fedora/kustomization.yaml
  preferences/fedora/s390x/kustomization.yaml
  preferences/fedora/s390x/metadata/kustomization.yaml
  preferences/fedora/s390x/metadata/metadata.yaml
  preferences/rhel/9/kustomization.yaml
  preferences/rhel/9/s390x/kustomization.yaml
  preferences/rhel/9/s390x/metadata/kustomization.yaml
  preferences/rhel/9/s390x/metadata/metadata.yaml
  preferences/rhel/9/s390x/requirements/kustomization.yaml
  preferences/rhel/9/s390x/requirements/requirements.yaml
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#308 [release-1.2] chore(test): Add CentOS Stream 10 func test.
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none
