Repository kubevirt/common-instancetypes, pull requests merged in 2024-11, with the labels that each got.

#258 centos, rhel: Fix DPDK preference requirements
  preferences/centos/8_stream_dpdk/requirements/requirements.yaml
  preferences/centos/9_stream_dpdk/requirements/requirements.yaml
  preferences/rhel/8_dpdk/requirements/requirements.yaml
  preferences/rhel/9_dpdk/requirements/requirements.yaml
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#268 Makefile: Remove whitespace from COMMON_INSTANCETYPES_IMAGE_TAG
  Makefile
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#271 Disable common instancetypes deployment by virt-operator
  scripts/kubevirt.sh
  scripts/kubevirtci.sh
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#274 Makefile, release-1.2: Pin to KubeVirt v1.4.0-rc.0 and release-1.4
  Makefile
  scripts/kubevirt.sh
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#276 Ensure `commonInstancetypesDeployment` is disabled, wait for resources to be deleted and stop using depreacted FGs
  scripts/kubevirt.sh
  scripts/kubevirtci.sh
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#269 Remove the deprecated `centos.7` and `centos.stream8` preferences
  README.md
  preferences/centos/7/kustomization.yaml
  preferences/centos/7/metadata/kustomization.yaml
  preferences/centos/7/metadata/metadata.yaml
  preferences/centos/7/requirements/kustomization.yaml
  preferences/centos/7/requirements/requirements.yaml
  preferences/centos/7_desktop/kustomization.yaml
  preferences/centos/8_stream/kustomization.yaml
  preferences/centos/8_stream/metadata/kustomization.yaml
  preferences/centos/8_stream/metadata/metadata.yaml
  preferences/centos/8_stream/requirements/kustomization.yaml
  preferences/centos/8_stream/requirements/requirements.yaml
  preferences/centos/8_stream_desktop/kustomization.yaml
  preferences/centos/8_stream_dpdk/kustomization.yaml
  preferences/centos/8_stream_dpdk/metadata/kustomization.yaml
  preferences/centos/8_stream_dpdk/metadata/metadata.yaml
  preferences/centos/8_stream_dpdk/requirements/kustomization.yaml
  preferences/centos/8_stream_dpdk/requirements/requirements.yaml
  preferences/centos/kustomization.yaml
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#275 Remove deprecated GN instance type class
  README.md
  docs/labels.md
  instancetypes/gn/1/gn1.yaml
  instancetypes/gn/1/kustomization.yaml
  instancetypes/gn/1/sizes.yaml
  instancetypes/gn/VirtualMachineClusterInstancetype/kustomization.yaml
  instancetypes/gn/VirtualMachineInstancetype/kustomization.yaml
  instancetypes/gn/kustomization.yaml
  instancetypes/kustomization.yaml
  scripts/deploy-kubevirt-and-cdi.sh
  tests/unittests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#279 feat: Disable Windows guest tests on architectures other than amd64
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#280 feat: enable Ubuntu common-instancetypes for s390x
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#283 [release-1.0] chore: Add flag for setting timeout for creating windows vms
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#282 [release-1.1] chore: Add flag for setting timeout for creating windows vms
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#285 feat: enable support for Fedora on s390x architecture
  README.md
  preferences/fedora/kustomization.yaml
  preferences/fedora/s390x/kustomization.yaml
  preferences/fedora/s390x/metadata/kustomization.yaml
  preferences/fedora/s390x/metadata/metadata.yaml
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, size/M, lgtm, approved, release-note-none

#288 add requirements into rhel.9.realtime preference
  preferences/rhel/9_realtime/kustomization.yaml
  preferences/rhel/9_realtime/requirements/kustomization.yaml
  preferences/rhel/9_realtime/requirements/requirements.yaml
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#289 [release-1.0] RHEL 10 Beta preference
  README.md
  preferences/rhel/10/amd64/kustomization.yaml
  preferences/rhel/10/amd64/metadata/kustomization.yaml
  preferences/rhel/10/amd64/metadata/metadata.yaml
  preferences/rhel/10/amd64/requirements/kustomization.yaml
  preferences/rhel/10/amd64/requirements/requirements.yaml
  preferences/rhel/10/kustomization.yaml
  preferences/rhel/kustomization.yaml
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, size/M, lgtm, release-note, approved

#290 feat: support RHEL 9 on s390x architecture
  README.md
  preferences/rhel/9/kustomization.yaml
  preferences/rhel/9/s390x/kustomization.yaml
  preferences/rhel/9/s390x/metadata/kustomization.yaml
  preferences/rhel/9/s390x/metadata/metadata.yaml
  preferences/rhel/9/s390x/requirements/kustomization.yaml
  preferences/rhel/9/s390x/requirements/requirements.yaml
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, size/M, lgtm, approved, release-note-none

#287 vm spec will use the preference requirements in vm creation test
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none
