Repository kubevirt/common-instancetypes, pull requests merged in 2024-08, with the labels that each got.

#216 [release-1.0] Revert "Remove Windows 2k12 template"
  README.md
  preferences/windows/2k12/kustomization.yaml
  preferences/windows/2k12/metadata/kustomization.yaml
  preferences/windows/2k12/metadata/metadata.yaml
  preferences/windows/2k12/requirements/kustomization.yaml
  preferences/windows/2k12/requirements/requirements.yaml
  preferences/windows/2k12_virtio/kustomization.yaml
  preferences/windows/2k12_virtio/metadata/kustomization.yaml
  preferences/windows/2k12_virtio/metadata/metadata.yaml
  preferences/windows/kustomization.yaml
Labels: dco-signoff: yes, size/M, lgtm, release-note, approved

#218 [release-1.1] kubevirt: Pin to KubeVirt 1.3 for testing
  Makefile
  scripts/kubevirt.sh
  scripts/kubevirtci.sh
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#215 feat(dpdk): Spread vCPUs across SocketsCoresThreads
  preferences/components/cpu-topology-spread/cpu-topology-spread.yaml
  preferences/rhel/8_dpdk/kustomization.yaml
  preferences/rhel/9_dpdk/kustomization.yaml
Labels: dco-signoff: yes, lgtm, size/XS, release-note, approved

#222 fix(rhel.9.realtime): Add display name override
  README.md
  preferences/rhel/9_realtime/metadata/metadata.yaml
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#224 chore: Update common-instancetypes-builder to use Fedora 40
  image/Dockerfile
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#226 Add dependabot configuration for tests
  .github/dependabot.yml
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#231 Add dependabot configuration for tools
  .github/dependabot.yml
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#230 fix(functests): Test rejection on insufficient resources separately
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#219 Add preferences for RHEL 10 Beta and CentOS 10 Stream
  README.md
  preferences/centos/10_stream/kustomization.yaml
  preferences/centos/10_stream/metadata/kustomization.yaml
  preferences/centos/10_stream/metadata/metadata.yaml
  preferences/centos/10_stream/requirements/kustomization.yaml
  preferences/centos/10_stream/requirements/requirements.yaml
  preferences/centos/10_stream_desktop/kustomization.yaml
  preferences/centos/kustomization.yaml
  preferences/components/efi/efi.yaml
  preferences/components/efi/kustomization.yaml
  preferences/rhel/10/amd64/kustomization.yaml
  preferences/rhel/10/amd64/metadata/kustomization.yaml
  preferences/rhel/10/amd64/metadata/metadata.yaml
  preferences/rhel/10/amd64/requirements/kustomization.yaml
  preferences/rhel/10/amd64/requirements/requirements.yaml
  preferences/rhel/10/arm64/kustomization.yaml
  preferences/rhel/10/arm64/metadata/kustomization.yaml
  preferences/rhel/10/arm64/metadata/metadata.yaml
  preferences/rhel/10/arm64/requirements/kustomization.yaml
  preferences/rhel/10/arm64/requirements/requirements.yaml
  preferences/rhel/10/kustomization.yaml
  preferences/rhel/kustomization.yaml
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#234 chore: Update common-instancetypes-builder
  Makefile
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#239 Add instancetype.kubevirt.io/size to all instance types
  instancetypes/cx/1/sizes.yaml
  instancetypes/gn/1/sizes.yaml
  instancetypes/m/1/sizes.yaml
  instancetypes/n/1/sizes.yaml
  instancetypes/o/1/sizes.yaml
  instancetypes/rt/1/sizes.yaml
  instancetypes/u/1/sizes.yaml
  tests/unittests/instancetype_test.go
Labels: dco-signoff: yes, size/M, lgtm, release-note, approved

#242 gn: Deprecate GPU NVIDIA class of instance types
  instancetypes/gn/1/gn1.yaml
Labels: dco-signoff: yes, lgtm, size/XS, release-note, approved, kind/deprecation
