Repository kubevirt/common-instancetypes, pull requests merged in 2024-07, with the labels that each got.

#189 scripts: Default COMMON_INSTANCETYPES_CRI to podman
  scripts/cri.sh
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#193 Introduce OpenSUSE Tumbleweed and Leap preferences
  README.md
  preferences/kustomization.yaml
  preferences/opensuse/kustomization.yaml
  preferences/opensuse/leap/kustomization.yaml
  preferences/opensuse/leap/metadata/kustomization.yaml
  preferences/opensuse/leap/metadata/metadata.yaml
  preferences/opensuse/leap/requirements/kustomization.yaml
  preferences/opensuse/leap/requirements/requirements.yaml
  preferences/opensuse/tumbleweed/kustomization.yaml
  preferences/opensuse/tumbleweed/metadata/kustomization.yaml
  preferences/opensuse/tumbleweed/metadata/metadata.yaml
  preferences/opensuse/tumbleweed/requirements/kustomization.yaml
  preferences/opensuse/tumbleweed/requirements/requirements.yaml
  scripts/cri.sh
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#195 Add SUSE Linux Enterprise Server (SLES) preference
  README.md
  preferences/kustomization.yaml
  preferences/sles/kustomization.yaml
  preferences/sles/metadata/kustomization.yaml
  preferences/sles/metadata/metadata.yaml
  preferences/sles/requirements/kustomization.yaml
  preferences/sles/requirements/requirements.yaml
  scripts/kubevirt.sh
  scripts/kubevirtci.sh
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
  tests/image/sles.Dockerfile
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#194 centos.7,centos.stream8: Mark as deprecated with recent EOLs
  preferences/centos/7/kustomization.yaml
  preferences/centos/8_stream/kustomization.yaml
Labels: dco-signoff: yes, lgtm, size/XS, release-note, approved

#198 kubevirt: Support kind kubevirtci providers
  scripts/kubevirt.sh
  scripts/kubevirtci.sh
  scripts/sync.sh
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#199 ubuntu: Add 24.04 test coverage
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#201 Fix instance type and preference unit tests
  tests/unittests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#200 docs: Add labels documentation
  README.md
  docs/labels.md
Labels: dco-signoff: yes, size/M, lgtm, approved, release-note-none

#203 preferences: Set vm.kubevirt.io/os within eventual VMI
  preferences/base/metadata/metadata.yaml
  preferences/windows/base/metadata/metadata.yaml
Labels: dco-signoff: yes, lgtm, size/XS, release-note, approved

#206 tests: Add VirtualMachine output on failure
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#209 u1.2xmedium: Add size to better align with Windows requirements
  README.md
  instancetypes/u/1/sizes.yaml
  tests/functests/instancetype_test.go
  tests/image/validationos.Dockerfile
  tests/scripts/build_windows_containerdisk/build.sh
Labels: dco-signoff: yes, lgtm, release-note, size/S, approved

#211 [release-0.4] u1.2xmedium: Add size to better align with Windows requirements
  README.md
  image/build_windows_containerdisk.sh
  image/validationos.Dockerfile
  instancetypes/u/1/sizes.yaml
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, release-note, size/S, approved

#196 feat: deploy and functest make tasks
  DEVELOPMENT.md
  Makefile
  scripts/deploy-kubevirt-and-cdi.sh
Labels: dco-signoff: yes, size/M, lgtm, approved, release-note-none

#205 fix: openapi2jsonlibrary incompatibility on s390x
  scripts/schema.sh
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#213 Remove Windows 2k12 template
  README.md
  preferences/windows/2k12/kustomization.yaml
  preferences/windows/2k12/metadata/kustomization.yaml
  preferences/windows/2k12/metadata/metadata.yaml
  preferences/windows/2k12/requirements/kustomization.yaml
  preferences/windows/2k12/requirements/requirements.yaml
  preferences/windows/2k12_virtio/kustomization.yaml
  preferences/windows/2k12_virtio/metadata/kustomization.yaml
  preferences/windows/2k12_virtio/metadata/metadata.yaml
  preferences/windows/kustomization.yaml
Labels: dco-signoff: yes, size/M, lgtm, release-note, approved
