Repository kubevirt/common-instancetypes, pull requests merged in 2025-06, with the labels that each got.

#387 m1, cx1: Introduce 1Gi hugepage sizes
  README.md
  docs/labels.md
  instancetypes/cx/1/cx1.yaml
  instancetypes/cx/1/sizes.yaml
  instancetypes/m/1/m1.yaml
  instancetypes/m/1/sizes.yaml
  instancetypes/n/1/n1.yaml
  instancetypes/rt/1/rt1.yaml
  tests/unittests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#386 feat(preferences): Add Windows 7
  README.md
  preferences/windows/7/kustomization.yaml
  preferences/windows/7/metadata/kustomization.yaml
  preferences/windows/7/metadata/metadata.yaml
  preferences/windows/7/requirements/kustomization.yaml
  preferences/windows/7/requirements/requirements.yaml
  preferences/windows/7_virtio/kustomization.yaml
  preferences/windows/7_virtio/metadata/kustomization.yaml
  preferences/windows/7_virtio/metadata/metadata.yaml
  preferences/windows/kustomization.yaml
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, size/M, lgtm, release-note, approved

#385 feat(preference): Add Windows Server 2008
  README.md
  preferences/windows/2k8/kustomization.yaml
  preferences/windows/2k8/metadata/kustomization.yaml
  preferences/windows/2k8/metadata/metadata.yaml
  preferences/windows/2k8/requirements/kustomization.yaml
  preferences/windows/2k8/requirements/requirements.yaml
  preferences/windows/2k8_virtio/kustomization.yaml
  preferences/windows/2k8_virtio/metadata/kustomization.yaml
  preferences/windows/2k8_virtio/metadata/metadata.yaml
  preferences/windows/kustomization.yaml
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#388 feat(preference): Add Windows Server 2012/2012 R2
  README.md
  preferences/windows/2k12/kustomization.yaml
  preferences/windows/2k12/metadata/kustomization.yaml
  preferences/windows/2k12/metadata/metadata.yaml
  preferences/windows/2k12/requirements/kustomization.yaml
  preferences/windows/2k12/requirements/requirements.yaml
  preferences/windows/2k12_virtio/kustomization.yaml
  preferences/windows/2k12_virtio/metadata/kustomization.yaml
  preferences/windows/2k12_virtio/metadata/metadata.yaml
  preferences/windows/kustomization.yaml
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#390 feat(preference): Add generic virtio transitional linux
  README.md
  preferences/components/virtio-transitional/kustomization.yaml
  preferences/components/virtio-transitional/virtio-transitional.yaml
  preferences/kustomization.yaml
  preferences/linux-virtio-transitional/kustomization.yaml
  preferences/linux-virtio-transitional/metadata/kustomization.yaml
  preferences/linux-virtio-transitional/metadata/metadata.yaml
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, size/M, lgtm, release-note, approved

#400 [release-1.0] chore(preference): Drop `Beta` from RHEL 10
  README.md
  preferences/rhel/10/amd64/metadata/metadata.yaml
Labels: dco-signoff: yes, lgtm, size/XS, release-note, approved

#398 [release-1.2] chore(preference): Drop `Beta` from RHEL 10
  README.md
  preferences/rhel/10/amd64/metadata/metadata.yaml
  preferences/rhel/10/arm64/metadata/metadata.yaml
Labels: dco-signoff: yes, lgtm, size/XS, release-note, approved

#401 tools: Use 1.24.4 toolchain version string
  tools/go.mod
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#404 chore(test): Add RHEL 7 and 8 preference tests
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none
