Repository kubevirt/common-instancetypes, pull requests merged in 2025-08, with the labels that each got.

#432 feat: add cpu.maxSockets to cx instance types
  instancetypes/cx/1/sizes.yaml
Labels: dco-signoff: yes, lgtm, release-note, size/S, approved

#437 [release-1.0] feat(preference): Add Windows Server 2008
  README.md
  preferences/windows/2k8/kustomization.yaml
  preferences/windows/2k8/metadata/kustomization.yaml
  preferences/windows/2k8/metadata/metadata.yaml
  preferences/windows/2k8/requirements/kustomization.yaml
  preferences/windows/2k8/requirements/requirements.yaml
  preferences/windows/2k8_virtio/kustomization.yaml
  preferences/windows/2k8_virtio/metadata/kustomization.yaml
  preferences/windows/2k8_virtio/metadata/metadata.yaml
  preferences/windows/kustomization.yaml
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#439 [release-1.0] feat(preference): Add Windows Server 2012/2012 R2
  README.md
  preferences/windows/2k12/kustomization.yaml
  preferences/windows/2k12/metadata/metadata.yaml
  preferences/windows/2k12/requirements/requirements.yaml
  preferences/windows/2k12_virtio/kustomization.yaml
  preferences/windows/2k12_virtio/metadata/metadata.yaml
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, release-note, size/S, approved

#441 [release-1.0] feat(preferences): Add Windows 7
  README.md
  preferences/windows/7/kustomization.yaml
  preferences/windows/7/metadata/kustomization.yaml
  preferences/windows/7/metadata/metadata.yaml
  preferences/windows/7/requirements/kustomization.yaml
  preferences/windows/7/requirements/requirements.yaml
  preferences/windows/7_virtio/kustomization.yaml
  preferences/windows/7_virtio/metadata/kustomization.yaml
  preferences/windows/7_virtio/metadata/metadata.yaml
  preferences/windows/kustomization.yaml
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, size/M, lgtm, release-note, approved

#440 [release-1.1] feat(preferences): Add Windows 7
  README.md
  preferences/windows/7/kustomization.yaml
  preferences/windows/7/metadata/kustomization.yaml
  preferences/windows/7/metadata/metadata.yaml
  preferences/windows/7/requirements/kustomization.yaml
  preferences/windows/7/requirements/requirements.yaml
  preferences/windows/7_virtio/kustomization.yaml
  preferences/windows/7_virtio/metadata/kustomization.yaml
  preferences/windows/7_virtio/metadata/metadata.yaml
  preferences/windows/kustomization.yaml
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, size/M, lgtm, release-note, approved

#447 chore(test): Add functional test for Debian 13
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none
