Repository kubevirt/common-instancetypes, pull requests merged in 2025-04, with the labels that each got.

#343 functests: Allow to specify arch to test preferences for
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#346 chore(preferences): Replace usage of `base` by `linux` preference
  preferences/alpine/kustomization.yaml
  preferences/centos/10_stream/kustomization.yaml
  preferences/centos/9_stream/kustomization.yaml
  preferences/centos/base/kustomization.yaml
  preferences/cirros/kustomization.yaml
  preferences/fedora/amd64/kustomization.yaml
  preferences/fedora/arm64/kustomization.yaml
  preferences/fedora/s390x/kustomization.yaml
  preferences/opensuse/leap/kustomization.yaml
  preferences/opensuse/tumbleweed/kustomization.yaml
  preferences/rhel/10/amd64/kustomization.yaml
  preferences/rhel/10/arm64/kustomization.yaml
  preferences/rhel/9/amd64/kustomization.yaml
  preferences/rhel/9/arm64/kustomization.yaml
  preferences/rhel/base/kustomization.yaml
  preferences/sles/kustomization.yaml
  preferences/ubuntu/kustomization.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved, release-note-none

#347 feat(preference): Add Oracle linux preference
  Makefile
  README.md
  preferences/kustomization.yaml
  preferences/oraclelinux/kustomization.yaml
  preferences/oraclelinux/metadata/kustomization.yaml
  preferences/oraclelinux/metadata/metadata.yaml
  preferences/oraclelinux/requirements/kustomization.yaml
  preferences/oraclelinux/requirements/requirements.yaml
  scripts/kubevirt.sh
  scripts/kubevirtci.sh
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
  tests/image/oraclelinux.Dockerfile
  tests/image/oraclelinux.tag
  tests/scripts/build-ol.sh
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#350 [release-1.2] Add generic linux distribution and legacy preference
  README.md
  docs/labels.md
  preferences/components/diskbus-scsi/diskbus-scsi.yaml
  preferences/components/diskbus-scsi/kustomization.yaml
  preferences/components/interfacemodel-e1000/e1000.yaml
  preferences/components/interfacemodel-e1000/kustomization.yaml
  preferences/kustomization.yaml
  preferences/legacy/kustomization.yaml
  preferences/legacy/metadata/kustomization.yaml
  preferences/legacy/metadata/metadata.yaml
  preferences/linux-efi/kustomization.yaml
  preferences/linux-efi/metadata/kustomization.yaml
  preferences/linux-efi/metadata/metadata.yaml
  preferences/linux/kustomization.yaml
  preferences/linux/metadata/kustomization.yaml
  preferences/linux/metadata/metadata.yaml
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#352 [release-1.0] Add generic linux distribution and legacy preference
  README.md
  docs/labels.md
  preferences/components/diskbus-scsi/diskbus-scsi.yaml
  preferences/components/diskbus-scsi/kustomization.yaml
  preferences/components/interfacemodel-e1000/e1000.yaml
  preferences/components/interfacemodel-e1000/kustomization.yaml
  preferences/kustomization.yaml
  preferences/legacy/kustomization.yaml
  preferences/legacy/metadata/kustomization.yaml
  preferences/legacy/metadata/metadata.yaml
  preferences/linux-efi/kustomization.yaml
  preferences/linux-efi/metadata/kustomization.yaml
  preferences/linux-efi/metadata/metadata.yaml
  preferences/linux/kustomization.yaml
  preferences/linux/metadata/kustomization.yaml
  preferences/linux/metadata/metadata.yaml
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#354 [release-1.2] feat(preferences): Add Debian and Oracle preferences
  Makefile
  README.md
  preferences/debian/kustomization.yaml
  preferences/debian/metadata/kustomization.yaml
  preferences/debian/metadata/metadata.yaml
  preferences/debian/requirements/kustomization.yaml
  preferences/debian/requirements/requirements.yaml
  preferences/kustomization.yaml
  preferences/oraclelinux/kustomization.yaml
  preferences/oraclelinux/metadata/kustomization.yaml
  preferences/oraclelinux/metadata/metadata.yaml
  preferences/oraclelinux/requirements/kustomization.yaml
  preferences/oraclelinux/requirements/requirements.yaml
  scripts/kubevirt.sh
  scripts/kubevirtci.sh
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
  tests/image/oraclelinux.Dockerfile
  tests/image/oraclelinux.tag
  tests/scripts/build-ol.sh
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#356 [release-1.1] feat(preferences): Add Debian and Oracle preferences
  Makefile
  README.md
  preferences/debian/kustomization.yaml
  preferences/debian/metadata/kustomization.yaml
  preferences/debian/metadata/metadata.yaml
  preferences/debian/requirements/kustomization.yaml
  preferences/debian/requirements/requirements.yaml
  preferences/kustomization.yaml
  preferences/oraclelinux/kustomization.yaml
  preferences/oraclelinux/metadata/kustomization.yaml
  preferences/oraclelinux/metadata/metadata.yaml
  preferences/oraclelinux/requirements/kustomization.yaml
  preferences/oraclelinux/requirements/requirements.yaml
  scripts/kubevirt.sh
  scripts/kubevirtci.sh
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
  tests/image/oraclelinux.Dockerfile
  tests/image/oraclelinux.tag
  tests/scripts/build-ol.sh
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#360 [release-1.0] feat(preferences): Add Debian and Oracle preferences
  Makefile
  README.md
  image/oraclelinux.Dockerfile
  image/oraclelinux.tag
  preferences/debian/kustomization.yaml
  preferences/debian/metadata/kustomization.yaml
  preferences/debian/metadata/metadata.yaml
  preferences/debian/requirements/kustomization.yaml
  preferences/debian/requirements/requirements.yaml
  preferences/kustomization.yaml
  preferences/oraclelinux/kustomization.yaml
  preferences/oraclelinux/metadata/kustomization.yaml
  preferences/oraclelinux/metadata/metadata.yaml
  preferences/oraclelinux/requirements/kustomization.yaml
  preferences/oraclelinux/requirements/requirements.yaml
  scripts/kubevirt.sh
  scripts/kubevirtci.sh
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
  tests/scripts/build-ol.sh
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#363 chore(kubevirtci): Stop deploying NFS
  scripts/kubevirt.sh
  scripts/kubevirtci.sh
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#364 chore(preferences): Switch `scsi` to `sata` in legacy
  preferences/legacy/kustomization.yaml
Labels: dco-signoff: yes, lgtm, size/XS, release-note, approved

#368 chore: Pin kubevirtci to version used by KUBEVIRT_VERSION
  scripts/kubevirtci.sh
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#369 [release-1.2] chore(Makefile): Pin KUBEVIRT_VERSION to v1.4.0
  Makefile
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#366 [release-1.3] chore(kubevirtci): Pin to KubeVirt v1.5.0
  Makefile
  scripts/kubevirt.sh
  scripts/kubevirtci.sh
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none
