Repository kubevirt/common-instancetypes, pull requests merged in 2025-03, with the labels that each got.

#325 image: Request a specific golang version in the builder Dockerfile
  image/Dockerfile
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#322 Add generic linux distribution and legacy preference
  README.md
  docs/labels.md
  preferences/components/diskbus-scsi/diskbus-scsi.yaml
  preferences/components/diskbus-scsi/kustomization.yaml
  preferences/components/interfacemodel-e1000/e1000.yaml
  preferences/components/interfacemodel-e1000/kustomization.yaml
  preferences/kustomization.yaml
  preferences/legacy/kustomization.yaml
  preferences/legacy/metadata/kustomization.yaml
  preferences/legacy/metadata/metadata.yaml
  preferences/linux-efi/kustomization.yaml
  preferences/linux-efi/metadata/kustomization.yaml
  preferences/linux-efi/metadata/metadata.yaml
  preferences/linux/kustomization.yaml
  preferences/linux/metadata/kustomization.yaml
  preferences/linux/metadata/metadata.yaml
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#332 tests: Add flag for expectedVendor to accommodate downstream modifications
  tests/unittests/instancetype_test.go
  tests/unittests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#331 feat(preferences): Add preference for Debian
  README.md
  preferences/debian/kustomization.yaml
  preferences/debian/metadata/kustomization.yaml
  preferences/debian/metadata/metadata.yaml
  preferences/debian/requirements/kustomization.yaml
  preferences/debian/requirements/requirements.yaml
  preferences/kustomization.yaml
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, size/M, lgtm, release-note, approved

#334 Add Debian requirements and avoid skip testing unintended preferences
  preferences/debian/kustomization.yaml
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#335 [release-1.3] feat(prefences): Add preference for Debian
  README.md
  preferences/debian/kustomization.yaml
  preferences/debian/metadata/kustomization.yaml
  preferences/debian/metadata/metadata.yaml
  preferences/debian/requirements/kustomization.yaml
  preferences/debian/requirements/requirements.yaml
  preferences/kustomization.yaml
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, size/M, lgtm, release-note, approved

#340 chore(tests): Wire up UNITTEST_EXTRA_ARGS
  Makefile
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none
