Repository kubevirt/common-instancetypes, pull requests merged in 2025-07, with the labels that each got.

#406 feat: e2e tests adjustments
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#418 Fix: remove extra ')' in KUBEVIRT_VERSION export
  scripts/kubevirtci.sh
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none

#419 Bump golangci-lint and golang versions
  .golangci.yml
  Makefile
  image/Dockerfile
  tests/functests/instancetype_test.go
  tests/go.mod
  tests/unittests/instancetype_test.go
  tests/unittests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/L, approved, release-note-none

#423 m1, cx1: Introduce 1Gi hugepage sizes
  README.md
  docs/labels.md
  instancetypes/cx/1/cx1.yaml
  instancetypes/cx/1/sizes.yaml
  instancetypes/m/1/m1.yaml
  instancetypes/m/1/sizes.yaml
  instancetypes/n/1/n1.yaml
  instancetypes/rt/1/rt1.yaml
  tests/unittests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#425 [release-1.1] m1, cx1: Introduce 1Gi hugepage sizes
  README.md
  docs/labels.md
  instancetypes/cx/1/cx1.yaml
  instancetypes/cx/1/sizes.yaml
  instancetypes/m/1/m1.yaml
  instancetypes/m/1/sizes.yaml
  instancetypes/n/1/n1.yaml
  instancetypes/rt/1/rt1.yaml
  tests/unittests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved
