Repository kubevirt/common-instancetypes, pull requests merged in 2025-05, with the labels that each got.

#361 feat: Add preferences for RHEL 10 Beta s390x
  README.md
  preferences/rhel/10/kustomization.yaml
  preferences/rhel/10/s390x/kustomization.yaml
  preferences/rhel/10/s390x/metadata/kustomization.yaml
  preferences/rhel/10/s390x/metadata/metadata.yaml
  preferences/rhel/10/s390x/requirements/kustomization.yaml
  preferences/rhel/10/s390x/requirements/requirements.yaml
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, size/M, lgtm, release-note, approved

#373 chore(lint): Fix warnings and drop use of relaxed `yamllint` profile
  preferences/base/metadata/metadata.yaml
  preferences/centos/9_stream_dpdk/requirements/requirements.yaml
  preferences/components/cpu-topology-spread/cpu-topology-spread.yaml
  preferences/legacy/metadata/kustomization.yaml
  preferences/rhel/8_dpdk/requirements/requirements.yaml
  preferences/rhel/9_dpdk/requirements/requirements.yaml
  scripts/lint.sh
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#376 fix(test): Split Oracle Linux tests in different archs
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#381 [release-1.1] fix(test): Split Oracle Linux tests in different archs
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/S, approved, release-note-none

#380 feat(preference): Add Windows XP preference
  README.md
  preferences/components/pcihole64/kustomization.yaml
  preferences/components/pcihole64/pcihole64.yaml
  preferences/windows/kustomization.yaml
  preferences/windows/xp/kustomization.yaml
  preferences/windows/xp/metadata/kustomization.yaml
  preferences/windows/xp/metadata/metadata.yaml
  preferences/windows/xp/requirements/kustomization.yaml
  preferences/windows/xp/requirements/requirements.yaml
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, lgtm, size/L, release-note, approved

#383 feat(preference): Add Windows Server 2003 preference
  README.md
  preferences/components/interfacemodel-rtl8139/kustomization.yaml
  preferences/components/interfacemodel-rtl8139/rtl8139.yaml
  preferences/windows/2k3/kustomization.yaml
  preferences/windows/2k3/metadata/kustomization.yaml
  preferences/windows/2k3/metadata/metadata.yaml
  preferences/windows/2k3/requirements/kustomization.yaml
  preferences/windows/2k3/requirements/requirements.yaml
  preferences/windows/kustomization.yaml
  tests/functests/instancetype_test.go
  tests/functests/test_suite_test.go
Labels: dco-signoff: yes, size/M, lgtm, release-note, approved

#384 chore(test): Drop ssh test in Windows XP
  tests/functests/instancetype_test.go
Labels: dco-signoff: yes, lgtm, size/XS, approved, release-note-none
